'use client';
import { useState, type ReactNode } from 'react';
type QcStatus='belum_dinilai'|'restock_layak'|'rusak'|'hilang';
type Item={noPesanan:string;sourceType:string;sourceReference:string|null;sourceStatus:string|null;reason:string|null;quantity:number|null;amount:number|null;stockStatus:string|null;sourceFile:string;qcStatus?:QcStatus;qcNote?:string};
type Order={no_pesanan:string;orderDate:string;settlement:number|null;totalHpp:number;profitActual:number|null;bucket:string};
type Data={dateRange:{dateFrom:string;dateTo:string};summary:{settledNormal:number;pending:number;exception:number;cancelled:number;settlement:number;hpp:number;profit:number};orders:Order[];exceptionDetails:Item[];returnQcReview:Item[]};
const idr=(v:number|null)=>v===null?'—':new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v);
const qc:Record<QcStatus,string>={belum_dinilai:'Belum dinilai',restock_layak:'Restock layak',rusak:'Rusak',hilang:'Hilang'};
export default function ProfitActualPanel({storeId,view}:{storeId:string;view:'actual'|'returns'}){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState<string|null>(null);
 const [dateFrom,setDateFrom]=useState('2026-08-01'),[dateTo,setDateTo]=useState('2026-08-31');
 const load=async()=>{if(!dateFrom||!dateTo||dateFrom>dateTo){setError('Rentang tanggal tidak valid.');return}setLoading(true);setError('');try{const params=new URLSearchParams({storeId,dateFrom,dateTo});const r=await fetch(`/api/profit-calculation?${params}`,{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error);setData(b)}catch(e){setError(e instanceof Error?e.message:'Gagal memuat data.')}finally{setLoading(false)}};
 const save=async(row:Item,status:QcStatus,note:string)=>{if(!row.sourceReference)return;setSaving(row.sourceReference);try{const r=await fetch('/api/return-qc',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({storeId,noPengembalian:row.sourceReference,noPesanan:row.noPesanan,qcStatus:status,qcNote:note})}),b=await r.json();if(!r.ok)throw Error(b.error);await load()}catch(e){setError(e instanceof Error?e.message:'Gagal simpan QC.')}finally{setSaving(null)}};
 const title=view==='actual'?'Profit Aktual':'Retur & Refund';
 return <><section className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><b>{title}.</b><p className="mt-1">{view==='actual'?'Khusus pesanan selesai dengan settlement Penghasilan / Order dan HPP valid.':'Return/refund, failed delivery, cancellation, adjustment, dan QC operasional. Tidak mengubah Profit Aktual.'}</p></section><section className="mb-5 rounded-xl border border-slate-200 bg-white p-4"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end"><label className="text-sm font-medium text-slate-700">Dari tanggal<input type="date" value={dateFrom} onChange={e=>{setDateFrom(e.target.value);setData(null)}} className="mt-1 block w-full rounded border border-slate-300 p-2"/></label><label className="text-sm font-medium text-slate-700">Sampai tanggal<input type="date" value={dateTo} onChange={e=>{setDateTo(e.target.value);setData(null)}} className="mt-1 block w-full rounded border border-slate-300 p-2"/></label><button onClick={()=>void load()} disabled={!storeId||loading} className="rounded-lg bg-purple-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{loading?'Memuat…':`Muat ${title}`}</button></div></section>{error&&<p className="mb-4 text-sm text-red-700">{error}</p>}{data&&<p className="mb-4 text-sm text-slate-600">Scope: <b>{data.dateRange.dateFrom}</b> s.d. <b>{data.dateRange.dateTo}</b></p>}{data&&(view==='actual'?<Actual data={data}/>:<Returns data={data} saving={saving} save={save}/>)}</>;
}
function Actual({data}:{data:Data}){return <><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card label="Profit Aktual" value={idr(data.summary.profit)} detail={`${data.summary.settledNormal} pesanan selesai`}/><Card label="Settlement" value={idr(data.summary.settlement)} detail="Penghasilan / Order"/><Card label="Total HPP" value={idr(data.summary.hpp)} detail="HPP valid"/><Card label="Belum Tersettle" value={String(data.summary.pending)} detail="Tidak masuk profit aktual"/></div><Table title="Profit Pesanan Selesai" scrollable headers={['Tanggal','No. Pesanan','Settlement','HPP','Profit Aktual']} rows={data.orders.filter(x=>x.bucket==='settled_normal').map(x=>[x.orderDate,x.no_pesanan,idr(x.settlement),idr(x.totalHpp),idr(x.profitActual)])}/></>}
function Returns({data,saving,save}:{data:Data;saving:string|null;save:(x:Item,s:QcStatus,n:string)=>Promise<void>}){return <><section className="mb-5 overflow-hidden rounded-xl border border-amber-200 bg-white"><div className="border-b border-amber-200 bg-amber-50 p-4"><b>Return QC Internal</b><p className="mt-1 text-sm text-slate-600">Keputusan QC audit-only, belum ada dampak finansial otomatis.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-sm"><thead><tr>{['Order','No. Pengembalian','Qty','Alasan','QC','Catatan','Aksi'].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{data.returnQcReview.map(x=><QcRow key={x.sourceReference} row={x} saving={saving===x.sourceReference} save={save}/>)}</tbody></table></div></section><Table title="Exception & Rekonsiliasi" headers={['Order','Jenis','Referensi','Status','Alasan','Qty','Nilai','Source RAW']} rows={data.exceptionDetails.map(x=>[x.noPesanan,x.sourceType,x.sourceReference||'—',x.sourceStatus||'—',x.reason||'—',x.quantity??'—',idr(x.amount),x.sourceFile])}/></>}
function QcRow({row,saving,save}:{row:Item;saving:boolean;save:(x:Item,s:QcStatus,n:string)=>Promise<void>}){const[s,setS]=useState<QcStatus>(row.qcStatus||'belum_dinilai'),[n,setN]=useState(row.qcNote||'');return <tr className="border-t"><td className="p-3">{row.noPesanan}</td><td className="p-3">{row.sourceReference}</td><td className="p-3">{row.quantity??'—'}</td><td className="p-3">{row.reason||'—'}</td><td className="p-3"><select value={s} onChange={e=>setS(e.target.value as QcStatus)} className="rounded border p-2">{Object.entries(qc).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td><td className="p-3"><input value={n} maxLength={2000} onChange={e=>setN(e.target.value)} className="w-60 rounded border p-2"/></td><td className="p-3"><button disabled={saving} onClick={()=>void save(row,s,n)} className="rounded bg-slate-800 px-3 py-2 text-white disabled:opacity-50">{saving?'Menyimpan…':'Simpan'}</button></td></tr>}
function Card({label,value,detail}:{label:string;value:string;detail:string}){return <section className="rounded-xl border bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></section>}
function Table({title,headers,rows,scrollable=false}:{title:string;headers:string[];rows:ReactNode[][];scrollable?:boolean}){return <section className="mt-5 overflow-hidden rounded-xl border bg-white"><div className="border-b p-4"><b>{title}</b>{scrollable&&<p className="mt-1 text-xs text-slate-500">Menampilkan area 9 baris; scroll vertikal untuk baris lainnya.</p>}</div><div className={scrollable?'max-h-[437px] overflow-auto':'overflow-x-auto'}><table className="w-full min-w-[800px] text-sm"><thead className={scrollable?'sticky top-0 z-10 bg-slate-50':'bg-slate-50'}><tr>{headers.map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} className="border-t">{r.map((x,j)=><td key={j} className="p-3">{x}</td>)}</tr>):<tr><td className="p-6" colSpan={headers.length}>Tidak ada data.</td></tr>}</tbody></table></div></section>}
