'use client';
import { useState, type ReactNode } from 'react';

type QcStatus='belum_dinilai'|'restock_layak'|'rusak'|'hilang';
type ExceptionDetail={noPesanan:string;sourceType:string;sourceReference:string|null;sourceStatus:string|null;reason:string|null;quantity:number|null;amount:number|null;stockStatus:string|null;sourceFile:string;reviewStatus?:string;financialTreatment?:string;qcStatus?:QcStatus;qcNote?:string;qcUpdatedAt?:string|null};
type Order={no_pesanan:string;orderDate:string;settlement:number|null;totalHpp:number;profitActual:number|null;bucket:string};
type Payload={summary:{settledNormal:number;pending:number;exception:number;cancelled:number;settlement:number;hpp:number;profit:number};orders:Order[];exceptionDetails:ExceptionDetail[];returnQcReview:ExceptionDetail[]};
const idr=(value:number|null)=>value===null?'—':new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value);
const bucket:Record<string,string>={settled_normal:'Tersettle Normal',pending:'Belum Tersettle',exception:'Perlu Finalisasi Exception',batal:'Tidak Ada Profit — Batal',hpp_issue:'Perlu Mapping HPP'};
const qcLabels:Record<QcStatus,string>={belum_dinilai:'Belum dinilai',restock_layak:'Restock layak',rusak:'Rusak',hilang:'Hilang'};

export default function ProfitActualPanel({storeId}:{storeId:string}){
 const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [saving,setSaving]=useState<string|null>(null);
 const load=async()=>{if(!storeId)return;setLoading(true);setError('');try{const response=await fetch(`/api/profit-calculation?storeId=${storeId}&dateFrom=2026-08-01&dateTo=2026-08-31`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body)}catch(caught){setError(caught instanceof Error?caught.message:'Gagal memuat Profit Aktual.')}finally{setLoading(false)}};
 const saveQc=async(row:ExceptionDetail,status:QcStatus,note:string)=>{if(!row.sourceReference)return;setSaving(row.sourceReference);setError('');try{const response=await fetch('/api/return-qc',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({storeId,noPengembalian:row.sourceReference,noPesanan:row.noPesanan,qcStatus:status,qcNote:note})});const body=await response.json();if(!response.ok)throw new Error(body.error);await load()}catch(caught){setError(caught instanceof Error?caught.message:'Gagal menyimpan QC.')}finally{setSaving(null)}};
 return <><section className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><b>Profit Aktual — cohort Agustus 2026.</b><p className="mt-1">Normal hanya memakai settlement `Penghasilan / Order` dikurangi HPP. Keputusan Return QC tersimpan untuk audit, tetapi belum mengubah HPP atau Profit Aktual Normal.</p></section><button type="button" onClick={()=>void load()} disabled={!storeId||loading} className="mb-5 rounded-lg bg-purple-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{loading?'Memuat…':'Muat Profit Aktual'}</button>{error&&<p className="mb-4 text-sm text-red-700">{error}</p>}{data&&<><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card label="Profit Aktual Normal" value={idr(data.summary.profit)} detail={`${data.summary.settledNormal} order settled normal`}/><Card label="Settlement Normal" value={idr(data.summary.settlement)} detail="Penghasilan / Order"/><Card label="Total HPP Normal" value={idr(data.summary.hpp)} detail="HPP item valid"/><Card label="Perlu Review" value={`${data.summary.pending+data.summary.exception}`} detail={`${data.summary.pending} belum settle · ${data.summary.exception} exception`}/></div><Table title="Profit Aktual per Order" note="Hanya Tersettle Normal masuk total." headers={['Tanggal','No. Pesanan','Bucket','Settlement','HPP','Profit Aktual']} rows={data.orders.map(o=>[o.orderDate,o.no_pesanan,bucket[o.bucket]||o.bucket,idr(o.settlement),idr(o.totalHpp),idr(o.profitActual)])}/><section className="mt-5 overflow-hidden rounded-xl border border-amber-200 bg-white"><div className="border-b border-amber-200 bg-amber-50 p-4"><b>Return QC Internal</b><p className="mt-1 text-sm text-slate-600">Simpan keputusan per No. Pengembalian. Audit operasional saja; belum ada dampak finansial otomatis.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-600"><tr><th className="p-3">Order</th><th className="p-3">No. Pengembalian</th><th className="p-3">Qty</th><th className="p-3">Alasan</th><th className="p-3">Status Shopee</th><th className="p-3">QC Internal</th><th className="p-3">Catatan</th><th className="p-3">Aksi</th></tr></thead><tbody>{data.returnQcReview.map(row=><QcRow key={row.sourceReference} row={row} saving={saving===row.sourceReference} onSave={saveQc}/>)}</tbody></table></div></section><Table title="Exception & Rekonsiliasi" note="Audit-only; tidak mengubah Profit Aktual Normal." headers={['Order','Jenis','Referensi','Status','Alasan','Qty','Nilai','QC Stok','Source RAW']} rows={data.exceptionDetails.map(x=>[x.noPesanan,x.sourceType.replace('_',' / '),x.sourceReference||'—',x.sourceStatus||'—',x.reason||'—',x.quantity??'—',idr(x.amount),x.stockStatus||'Menunggu QC / N/A',x.sourceFile])}/></>}</>;
}
function QcRow({row,saving,onSave}:{row:ExceptionDetail;saving:boolean;onSave:(row:ExceptionDetail,status:QcStatus,note:string)=>Promise<void>}){const [status,setStatus]=useState<QcStatus>(row.qcStatus||'belum_dinilai');const [note,setNote]=useState(row.qcNote||'');return <tr className="border-t align-top"><td className="p-3 font-medium">{row.noPesanan}</td><td className="p-3">{row.sourceReference||'—'}</td><td className="p-3">{row.quantity??'—'}</td><td className="p-3">{row.reason||'—'}</td><td className="p-3">{row.stockStatus||'—'}</td><td className="p-3"><select value={status} onChange={e=>setStatus(e.target.value as QcStatus)} className="rounded border border-slate-300 p-2">{Object.entries(qcLabels).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></td><td className="p-3"><input value={note} maxLength={2000} onChange={e=>setNote(e.target.value)} className="w-64 rounded border border-slate-300 p-2" placeholder="Catatan QC opsional"/></td><td className="p-3"><button type="button" disabled={saving} onClick={()=>void onSave(row,status,note)} className="rounded bg-slate-800 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">{saving?'Menyimpan…':'Simpan QC'}</button></td></tr>}
function Card({label,value,detail}:{label:string;value:string;detail:string}){return <section className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></section>}
function Table({title,note,headers,rows}:{title:string;note:string;headers:string[];rows:ReactNode[][]}){return <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b p-4"><b>{title}</b><p className="mt-1 text-sm text-slate-500">{note}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-600"><tr>{headers.map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.length===0?<tr><td colSpan={headers.length} className="p-8 text-center text-slate-500">Tidak ada data pada cohort.</td></tr>:rows.map((row,index)=><tr key={index} className="border-t align-top">{row.map((cell,i)=><td key={i} className="p-3">{cell}</td>)}</tr>)}</tbody></table></div></section>}
