'use client';

import { Fragment, useState } from 'react';

type Event = { at: string | null; type: string; direction: string; amount: number; description: string; status?: string | null; balanceAfter?: number | null; sourceFile: string | null; sourceRow: number | null };
type Row = { noPesanan: string; orderDate: string; statusPesanan: string | null; orderedPcs: number; returnedPcs: number; nonReturnedPcs: number; incomeSettlement: number; balanceOrderIncomeIn: number; balanceOrderIncomeOut: number; balanceAdjustmentIn: number; balanceAdjustmentOut: number; balanceNet: number; incomeBalanceDifference: number; exceptionTypes: string[]; reconciliationStatus: string; events: Event[] };
type Summary = { cohortOrders: number; incomeSettlement: number; balanceOrderIncomeIn: number; balanceOrderIncomeOut: number; balanceAdjustmentIn: number; balanceAdjustmentOut: number; balanceNet: number; matchNormal: number; reversal: number; adjustment: number; exception: number; partialReturnPending: number; needsReconciliation: number; noBalance: number };
type Data = { dateRange: { dateFrom: string; dateTo: string }; summary: Summary; rows: Row[] };

const idr = (value: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);
const statusClass = (value: string) => value === 'Match normal' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : value.includes('Retur parsial') ? 'bg-amber-50 text-amber-800 border-amber-200' : value.includes('pembalikan') || value.includes('Keluar') ? 'bg-rose-50 text-rose-700 border-rose-200' : 'bg-slate-100 text-slate-700 border-slate-200';

export default function SettlementBalanceReconciliationPanel({ storeId }: { storeId: string }) {
  const [dateFrom, setDateFrom] = useState('2026-08-01'); const [dateTo, setDateTo] = useState('2026-08-31');
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [open, setOpen] = useState<string | null>(null);
  const clear = () => setData(null);
  const load = async () => { if (!dateFrom || !dateTo || dateFrom > dateTo) { setError('Rentang Waktu Pesanan Dibuat tidak valid.'); return; } setLoading(true); setError(''); try { const params = new URLSearchParams({ storeId, dateFrom, dateTo }); const response = await fetch(`/api/settlement-balance-reconciliation?${params}`, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw Error(body.error || 'Gagal memuat rekonsiliasi.'); setData(body); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Gagal memuat rekonsiliasi.'); } finally { setLoading(false); } };
  return <>
    <section className="mb-5 rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-sm text-indigo-950"><b>Rekonsiliasi Settlement & My Balance.</b><p className="mt-1">Audit cashflow per No. Pesanan. Tidak mengubah Profit Aktual Normal, HPP normal, atau Return QC.</p></section>
    <section className="mb-5 rounded-xl border border-slate-200 bg-white p-4 sm:p-5"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end"><DateInput label="Dari Waktu Pesanan Dibuat" value={dateFrom} onChange={(value) => { setDateFrom(value); clear(); }} /><DateInput label="Sampai Waktu Pesanan Dibuat" value={dateTo} onChange={(value) => { setDateTo(value); clear(); }} /><button onClick={() => void load()} disabled={!storeId || loading} className="min-h-10 rounded-lg bg-purple-600 px-5 py-2 text-sm font-semibold text-white hover:bg-purple-700 disabled:opacity-50">{loading ? 'Memuat…' : 'Muat Rekonsiliasi'}</button></div><p className="mt-3 text-xs text-slate-500">Cohort memakai Waktu Pesanan Dibuat. My Balance dibaca sebagai event masuk/keluar terkait order, bukan sebagai pengganti settlement Income.</p></section>
    {error && <p className="mb-4 text-sm text-red-700">{error}</p>}
    {data && <><p className="mb-4 text-sm text-slate-600">Cohort pesanan dibuat: <b>{data.dateRange.dateFrom}</b> s.d. <b>{data.dateRange.dateTo}</b></p><SummaryCards summary={data.summary} /><section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-4"><b>Rekonsiliasi per Pesanan</b><p className="mt-1 text-xs text-slate-500">Satu baris per No. Pesanan. Klik detail untuk kronologi Income dan My Balance beserta provenance.</p></div><div className="max-h-[600px] overflow-auto"><table className="w-full min-w-[1450px] text-sm"><thead className="sticky top-0 z-10 bg-slate-50"><tr>{['Tanggal Order','No. Pesanan','Status Rekonsiliasi','Income / Order','Balance Masuk','Balance Keluar','Adjustment','Net Balance','Exception','Aksi'].map((label) => <th key={label} className="p-3 text-left text-xs font-semibold uppercase text-slate-600">{label}</th>)}</tr></thead><tbody>{data.rows.map((row) => <Fragment key={row.noPesanan}><tr className="border-t align-top hover:bg-slate-50"><td className="p-3">{row.orderDate}</td><td className="p-3 font-medium">{row.noPesanan}</td><td className="p-3"><span className={`inline-flex rounded-full border px-2 py-1 text-xs font-semibold ${statusClass(row.reconciliationStatus)}`}>{row.reconciliationStatus}</span></td><td className="p-3 tabular-nums">{idr(row.incomeSettlement)}</td><td className="p-3 tabular-nums text-emerald-700">{idr(row.balanceOrderIncomeIn)}</td><td className="p-3 tabular-nums text-rose-700">{idr(row.balanceOrderIncomeOut)}</td><td className="p-3 tabular-nums">{idr(row.balanceAdjustmentIn + row.balanceAdjustmentOut)}</td><td className="p-3 font-semibold tabular-nums">{idr(row.balanceNet)}</td><td className="p-3">{row.exceptionTypes.join(', ') || '—'}</td><td className="p-3"><button onClick={() => setOpen(open === row.noPesanan ? null : row.noPesanan)} className="rounded border border-purple-300 px-3 py-1.5 text-xs font-semibold text-purple-700">{open === row.noPesanan ? 'Tutup' : 'Lihat detail'}</button></td></tr>{open === row.noPesanan && <tr className="border-t bg-slate-50"><td colSpan={10} className="p-4"><OrderDetail row={row} /></td></tr>}</Fragment>)}</tbody></table></div></section></>}
  </>;
}
function DateInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm font-medium text-slate-700">{label}<input type="date" value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-300 p-2 text-sm" /></label>; }
function SummaryCards({ summary }: { summary: Summary }) { const cards: [string, number, string][] = [['Settlement Income / Order',summary.incomeSettlement,'Sumber settlement utama'],['My Balance · Penghasilan Masuk',summary.balanceOrderIncomeIn,'Cash masuk terkait order'],['My Balance · Penghasilan Keluar',summary.balanceOrderIncomeOut,'Pembalikan/deduksi saldo'],['My Balance · Penyesuaian Keluar',summary.balanceAdjustmentOut,'Audit-only, belum dibebankan profit'],['Net My Balance terkait order',summary.balanceNet,'Seluruh mutasi linked order'],['Perlu Rekonsiliasi',summary.reversal + summary.adjustment + summary.exception + summary.partialReturnPending + summary.needsReconciliation,`${summary.cohortOrders} order cohort · ${summary.matchNormal} match normal`]]; return <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label, value, detail]) => <section key={label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-bold tabular-nums text-slate-900">{label === 'Perlu Rekonsiliasi' ? value.toLocaleString('id-ID') : idr(value)}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></section>)}</div>; }
function OrderDetail({ row }: { row: Row }) { return <div className="grid gap-4 lg:grid-cols-[300px_1fr]"><div className="rounded-lg border bg-white p-3 text-sm"><p className="font-semibold">Ringkasan order</p><dl className="mt-2 grid grid-cols-2 gap-2"><dt>Status Shopee</dt><dd>{row.statusPesanan || '—'}</dd><dt>Qty</dt><dd>{row.nonReturnedPcs} tetap · {row.returnedPcs} retur</dd><dt>Income vs Balance masuk</dt><dd>{idr(row.incomeBalanceDifference)} selisih</dd><dt>Net My Balance</dt><dd>{idr(row.balanceNet)}</dd></dl></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-white"><tr>{['Waktu','Sumber / Jenis','Arah','Nominal','Deskripsi','Status','Saldo Setelah','Provenance'].map((label) => <th key={label} className="p-2 text-left">{label}</th>)}</tr></thead><tbody>{row.events.map((event, index) => <tr key={index} className="border-t"><td className="p-2 whitespace-nowrap">{event.at || '—'}</td><td className="p-2">{event.type}</td><td className="p-2">{event.direction}</td><td className={`p-2 tabular-nums ${event.amount < 0 ? 'text-rose-700' : 'text-emerald-700'}`}>{idr(event.amount)}</td><td className="p-2">{event.description}</td><td className="p-2">{event.status || '—'}</td><td className="p-2 tabular-nums">{event.balanceAfter === null || event.balanceAfter === undefined ? '—' : idr(event.balanceAfter)}</td><td className="p-2 text-xs text-slate-500">{event.sourceFile || '—'} · row {event.sourceRow ?? '—'}</td></tr>)}</tbody></table></div></div>; }
